version: '3'
services:
  blogito_postgresql:
    image: postgres:12
    container_name: blogito_postgresql
    volumes:
    - blogito_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - blogito_network
volumes:
  blogito_postgresql:
    external: true
networks:
  blogito_network:
    external: true